name: Build

on:
    workflow_dispatch:
    push:
        branches:
            - main

env:
    DOTNET_VERSION: "9.x"

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            runs:
                working-directory: BaseDotNetProjectSetup

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: ${{ env.DOTNET_VERSION }}

            - name: Restore
              run: |
                  dotnet restore BaseDotNetProjectSetup.sln

            - name: Build
              run: dotnet build BaseDotNetProjectSetup.sln --configuration Release --no-restore

            - name: Test
              run: dotnet test BaseDotNetProjectSetup.sln --configuration Release --no-restore --no-build

            - name: Publish
              run: dotnet publish BaseDotNetProjectSetup.sln --configuration Release --no-restore --no-build